// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azzyyzympmwrwrjburer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6enl5enltcG13cndyamJ1cmVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTA1MzEsImV4cCI6MjA3MTI2NjUzMX0.UiupCRjMQF3m98tNQiGLrIt-XnyVp-G8y2ksAJek7qY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});